// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	payFieldNames          = builder.RawFieldNames(&Pay{})
	payRows                = strings.Join(payFieldNames, ",")
	payRowsExpectAutoSet   = strings.Join(stringx.Remove(payFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	payRowsWithPlaceHolder = strings.Join(stringx.Remove(payFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cachePayIdPrefix = "cache:pay:id:"
	cachePayOidPrefix = "cache:pay:oid:"
)

type (
	payModel interface {
		Insert(ctx context.Context, data *Pay) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Pay, error)
		FindOneByOid(oid int64) (*Pay, error)
		Update(ctx context.Context, data *Pay) error
		Delete(ctx context.Context, id int64) error
	}

	defaultPayModel struct {
		sqlc.CachedConn
		table string
	}

	Pay struct {
		Id         int64     `db:"id"`
		Uid        int64     `db:"uid"`    // 用户ID
		Oid        int64     `db:"oid"`    // 订单ID
		Amount     int64     `db:"amount"` // 产品金额
		Source     int64     `db:"source"` // 支付方式
		Status     int64     `db:"status"` // 支付状态
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
	}
)

func newPayModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultPayModel {
	return &defaultPayModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`pay`",
	}
}

func (m *defaultPayModel) Delete(ctx context.Context, id int64) error {
	payIdKey := fmt.Sprintf("%s%v", cachePayIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, payIdKey)
	return err
}

func (m *defaultPayModel) FindOne(ctx context.Context, id int64) (*Pay, error) {
	payIdKey := fmt.Sprintf("%s%v", cachePayIdPrefix, id)
	var resp Pay
	err := m.QueryRowCtx(ctx, &resp, payIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", payRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPayModel) FindOneByOid(oid int64) (*Pay, error) {
	payOidKey := fmt.Sprintf("%s%v", cachePayOidPrefix, oid) //构造缓存键 payOidKey，格式化为 cachePayOidPrefix 和 oid 的组合字符串。cachePayOidPrefix 是缓存前缀，oid 是订单 ID。
	var resp Pay //声明一个 Pay 结构体变量 resp，用于存储从数据库查询的支付记录。
	err := m.QueryRow(&resp, payOidKey, func(conn sqlx.SqlConn, v interface{}) error {
		/*
		调用 m.QueryRow 方法，传入参数：
			&resp：查询结果存储的变量地址。
			payOidKey：缓存键。
			一个查询函数，执行数据库查询：
				构建查询语句，选择字段 payRows 从 m.table 表中查找 oid 为 ? 的记录，限制返回一条。
				使用 conn.QueryRow 执行 SQL 查询，将查询结果存入 v。
		 */
		query := fmt.Sprintf("select %s from %s where `oid` = ? limit 1", payRows, m.table)
		return conn.QueryRow(v, query, oid)
	})

	/*
	根据查询结果 err 进行处理：
		如果 err 为 nil，返回查询结果 &resp 和 nil 错误。
		如果 err 为 sqlc.ErrNotFound，返回 nil 和 ErrNotFound 错误。
		其他错误，直接返回错误 err。
	 */
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPayModel) Insert(ctx context.Context, data *Pay) (sql.Result, error) {
	payIdKey := fmt.Sprintf("%s%v", cachePayIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, payRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Uid, data.Oid, data.Amount, data.Source, data.Status)
	}, payIdKey)
	return ret, err
}

func (m *defaultPayModel) Update(ctx context.Context, data *Pay) error {
	payIdKey := fmt.Sprintf("%s%v", cachePayIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, payRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Uid, data.Oid, data.Amount, data.Source, data.Status, data.Id)
	}, payIdKey)
	return err
}

func (m *defaultPayModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePayIdPrefix, primary)
}

func (m *defaultPayModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", payRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultPayModel) tableName() string {
	return m.table
}
